server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      encoding: UTF-8

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: chess-ancient-manuscript-jwt-secret-key-2024-very-long-key
  expiration: 86400000
